INSERT INTO
    folders (account_id, name)
VALUES
    (1, 'Folder 1'),
    (1, 'Folder 2'),
    (2, 'Folder 3'),
    (2, 'Folder 4');

INSERT INTO
    subscriptions (
        account_id,
        parent_folder,
        xml_url,
        html_url,
        title,
        text,
        description,
        type,
        version,
        is_comment,
        is_breakpoint,
        created,
        category,
        language
    )
VALUES
    (
        1,
        'Folder 1',
        'https://example.com/rss-1.xml',
        'https://example-01.com/',
        'Feed Name 01',
        'Text Feed Name 01',
        'Feed Description',
        'rss',
        'RSS',
        FALSE,
        FALSE,
        '2022-01-01',
        'Category',
        'en'
    ),
    (
        1,
        'Folder 2',
        'https://example.com/rss-2.xml',
        'https://example-02.com/',
        'Feed Name 02',
        'Text Feed Name 02',
        'Feed Description',
        'rss',
        'RSS',
        FALSE,
        FALSE,
        '2022-01-01',
        'Category',
        'en'
    ),
    (
        1,
        NULL,
        'https://example.com/rss-4.xml',
        'https://example-04.com/',
        'Feed Name 04',
        'Text Feed Name 04',
        'Feed Description',
        'rss',
        'RSS',
        FALSE,
        FALSE,
        '2022-01-01',
        'Category',
        'en'
    ),
    (
        2,
        'Folder 3',
        'https://example.com/rss-5.xml',
        'https://example-05.com/',
        'Feed Name 05',
        'Text Feed Name 05',
        'Feed Description',
        'rss',
        'RSS',
        FALSE,
        FALSE,
        '2022-01-01',
        'Category',
        'en'
    ),
    (
        2,
        'Folder 4',
        'https://example.com/rss-6.xml',
        'https://example-06.com/',
        'Feed Name 06',
        'Text Feed Name 06',
        'Feed Description',
        'rss',
        'RSS',
        FALSE,
        FALSE,
        '2022-01-01',
        'Category',
        'en'
    ),
    (
        2,
        NULL,
        'https://example.com/rss-7.xml',
        'https://example-07.com/',
        'Feed Name 07',
        'Text Feed Name 07',
        'Feed Description',
        'rss',
        'RSS',
        FALSE,
        FALSE,
        '2022-01-01',
        'Category',
        'en'
    );
