[build]
target = "./index.html"
minify = "always"

[watch]
ignore = ["./src-tauri"]

[serve]
port = 1420
open = false

[tools]
# https://github.com/dobicinaitis/tailwind-cli-extra
tailwindcss = "2.1.6"
