name = "Crab News"
authors = ["Andrea Callea"]
repository = "https://github.com/crabapps/crab-news"
description = "A multi-platform RSS client for desktop and mobile"

[shells.android]
template = "android"
source = "android"
cores = ["shared"]

[shells.ios]
template = "ios"
source = "ios"
cores = ["shared"]

[shells.macos]
template = "macos"
source = "macos"
cores = ["shared"]

[shells.tui]
template = "tui"
source = "ratatui"
cores = ["shared"]

[cores.shared]
source = "shared"
type_gen = "shared_types"
crux_version = "0.6.3"

[shells.tauri]
template = "tauri"
source = "tauri"
cores = ["shared"]
